name: daily-build

on:
    push:
        branches:
            - master
#   schedule:
#     - cron: '0 0 * * *'

jobs:
    Build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
              node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - run: git submodule update --init --recursive
            - run: npm ci
            - run: cd zx && npm ci
            - run: node build.mjs

            - uses: actions/github-script@v6
              with:
                  script: |
                    const version = require('./zx/package.json').version
                    const response = await github.rest.repos.listTags({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                    })
                    if(response.data.some(i=>i.name===version)){
                        console.log(`Tag ${version} already exists`)
                    }else{
                        const release = await github.rest.repos.createRelease({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          tag_name: version
                        })
                        await github.rest.repos.uploadReleaseAsset({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          release_id: release.data.id,
                          name: 'zx.mjs',
                          data: require('fs').readFileSync('./dist/zx.mjs')
                        })
                    }
                    